imports:
  - { resource: config.yml }

framework:
  router:
    resource: '%kernel.root_dir%/config/routing_dev.yml'
    strict_requirements: true
  profiler: { only_exceptions: false }
  session:
    handler_id: session.handler.native_file
    save_path: '%env(DEV_FRAMEWORK_SESSION_SAVE_PATH)%'
  mailer:

web_profiler:
  toolbar: true
  intercept_redirects: false
  excluded_ajax_paths: '^/((index|app(_[\w]+)?)\.php/)?_wdt|\/feature\/metrics'

monolog:
  handlers:
    main:
      type: stream
      path: '%kernel.logs_dir%/%kernel.environment%.log'
      level: debug
      channels: [ '!event' ]

    console:
      type: console
      channels: [ '!event', '!doctrine' ]
    # uncomment to get logging in your browser
    # you may have to allow bigger header sizes in your Web server configuration
    #firephp:
    #    type: firephp
    #    level: info
    #chromephp:
    #    type: chromephp
    #    level: info

maker:
  root_namespace: 'AppBundle'

doctrine:
  dbal:
    profiling_collect_backtrace: true